### ISSUE TITLE
"Missing ./redis specifier in package"

### ISSUE THREAD

**Issue by IT-ess** [MacFJA/sveltekit-session#1]
I tried it on [StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-dn9q2j?file=src/hooks.server.ts), to assure it doesn't come from my config, but I can't use Redis a session storage. 

I get this weird error when I run `vite dev` : 
```
Error: Missing "./redis" specifier in "@macfja/sveltekit-session" package
    at e (file://file:///home/projects/sveltejs-kit-template-default-dn9q2j/node_modules/vite/dist/node/chunks/dep-ca21228b.js:14893:25)
    at n (file://file:///home/projects/sveltejs-kit-template-default-dn9q2j/node_modules/vite/dist/node/chunks/dep-ca21228b.js:14893:627)
    at o (file://file:///home/projects/sveltejs-kit-template-default-dn9q2j/node_modules/vite/dist/node/chunks/dep-ca21228b.js:14893:1276)
    at resolveExports (file://file:///home/projects/sveltejs-kit-template-default-dn9q2j/node_modules/vite/dist/node/chunks/dep-ca21228b.js:22081:21)
    at resolveDeepImport (file://file:///home/projects/sveltejs-kit-template-default-dn9q2j/node_modules/vite/dist/node/chunks/dep-ca21228b.js:22100:45)
    at tryNodeResolve (file://file:///home/projects/sveltejs-kit-template-default-dn9q2j/node_modules/vite/dist/node/chunks/dep-ca21228b.js:21785:20)
    at resolveId (file://file:///home/projects/sveltejs-kit-template-default-dn9q2j/node_modules/vite/dist/node/chunks/dep-ca21228b.js:21536:28)
    at resolveId (file://file:///home/projects/sveltejs-kit-template-default-dn9q2j/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41660:46)
    at <anonymous> (<anonymous>)
```

You can reproduce it on the stackblitz I shared. If you have any clue :pray:

**Comment by IT-ess** [comment]
Apparently it was a known bug, fixed with SvelteKit [1.6.0](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#160). I'll check later if it works now

**Comment by MacFJA** [comment]
Keep me in touch if it solved your issue

**Comment by IT-ess** [comment]
Still not working with SvelteKit 1.10.0 :-( 

The stack trace is slightly different, but it seems that redis is in fault. 
I saw in your package.json that `@redis/client` was in dev dependencies rather than in dependencies. Maybe it's the reason of this bug ?
